services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: fmis
      POSTGRES_USER: fmis
      POSTGRES_PASSWORD: fmis
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
